CREATE TABLE `BinaryOptionData`.`CURRENCY:EURUSD` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DateTime` DATETIME NOT NULL,
  `Price` DOUBLE NOT NULL,
  PRIMARY KEY (`ID`));
  
CREATE TABLE `BinaryOptionData`.`CURRENCY:GBPUSD` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DateTime` DATETIME NOT NULL,
  `Price` DOUBLE NOT NULL,
  PRIMARY KEY (`ID`));
  
CREATE TABLE `BinaryOptionData`.`CURRENCY:USDJPY` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DateTime` DATETIME NOT NULL,
  `Price` DOUBLE NOT NULL,
  PRIMARY KEY (`ID`));
  
CREATE TABLE `BinaryOptionData`.`CURRENCY:EURJPY` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DateTime` DATETIME NOT NULL,
  `Price` DOUBLE NOT NULL,
  PRIMARY KEY (`ID`));
  
CREATE TABLE `BinaryOptionData`.`CURRENCY:AUDUSD` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DateTime` DATETIME NOT NULL,
  `Price` DOUBLE NOT NULL,
  PRIMARY KEY (`ID`));
  
CREATE TABLE `BinaryOptionData`.`CURRENCY:USDCAD` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DateTime` DATETIME NOT NULL,
  `Price` DOUBLE NOT NULL,
  PRIMARY KEY (`ID`));
  
CREATE TABLE `BinaryOptionData`.`CURRENCY:GBPJPY` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DateTime` DATETIME NOT NULL,
  `Price` DOUBLE NOT NULL,
  PRIMARY KEY (`ID`));
  
CREATE TABLE `BinaryOptionData`.`CURRENCY:USDCHF` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DateTime` DATETIME NOT NULL,
  `Price` DOUBLE NOT NULL,
  PRIMARY KEY (`ID`));
  
CREATE TABLE `BinaryOptionData`.`CURRENCY:EURGBP` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DateTime` DATETIME NOT NULL,
  `Price` DOUBLE NOT NULL,
  PRIMARY KEY (`ID`));
  
CREATE TABLE `BinaryOptionData`.`CURRENCY:AUDJPY` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DateTime` DATETIME NOT NULL,
  `Price` DOUBLE NOT NULL,
  PRIMARY KEY (`ID`));
  
CREATE TABLE `BinaryOptionData`.`INDEXDJX:.DJI` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DateTime` DATETIME NOT NULL,
  `Price` DOUBLE NOT NULL,
  PRIMARY KEY (`ID`));
  
CREATE TABLE `BinaryOptionData`.`INDEXSP:.INX` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DateTime` DATETIME NOT NULL,
  `Price` DOUBLE NOT NULL,
  PRIMARY KEY (`ID`));
  
CREATE TABLE `BinaryOptionData`.`INDEXNASDAQ:.IXIC` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DateTime` DATETIME NOT NULL,
  `Price` DOUBLE NOT NULL,
  PRIMARY KEY (`ID`));
  
CREATE TABLE `BinaryOptionData`.`INDEXRUSSELL:RUT` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DateTime` DATETIME NOT NULL,
  `Price` DOUBLE NOT NULL,
  PRIMARY KEY (`ID`));
  
CREATE TABLE `BinaryOptionData`.`INDEXFTSE:XIN0` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DateTime` DATETIME NOT NULL,
  `Price` DOUBLE NOT NULL,
  PRIMARY KEY (`ID`));
  
CREATE TABLE `BinaryOptionData`.`INDEXFTSE:UKX` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DateTime` DATETIME NOT NULL,
  `Price` DOUBLE NOT NULL,
  PRIMARY KEY (`ID`));
  
CREATE TABLE `BinaryOptionData`.`INDEXFTSE:WIDEU` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DateTime` DATETIME NOT NULL,
  `Price` DOUBLE NOT NULL,
  PRIMARY KEY (`ID`));
  
CREATE TABLE `BinaryOptionData`.`INDEXFTSE:JAPAN` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DateTime` DATETIME NOT NULL,
  `Price` DOUBLE NOT NULL,
  PRIMARY KEY (`ID`));
